In [3]:
!git clone https://github.com/bgshih/coco-text.git

fatal: destination path 'coco-text' already exists and is not an empty directory.

In [18]:
# Import Python Standard Library dependencies
import datetime
from functools import partial
from glob import glob
import json
import math
import multiprocessing
import os
from pathlib import Path
import random
from typing import Any, Dict, Optional




# Import matplotlib for creating plots
import matplotlib.pyplot as plt

# Import numpy
import numpy as np

# Import the pandas package
import pandas as pd

# Set options for Pandas DataFrame display
pd.set_option('max_colwidth', None)  # Do not truncate the contents of cells in the DataFrame
pd.set_option('display.max_rows', None)  # Display all rows in the DataFrame
pd.set_option('display.max_columns', None)  # Display all columns in the DataFrame

# Import PIL for image manipulation
from PIL import Image, ImageDraw

# Import PyTorch dependencies
import torch
from torch.amp import autocast
from torch.cuda.amp import GradScaler
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision
torchvision.disable_beta_transforms_warning()
from torchvision.tv_tensors import BoundingBoxes, Mask
from torchvision.utils import draw_bounding_boxes, draw_segmentation_masks
import torchvision.transforms.v2  as transforms
from torchvision.transforms.v2 import functional as TF

# Import Mask R-CNN
from torchvision.models.detection import maskrcnn_resnet50_fpn_v2, MaskRCNN
from torchvision.models.detection import MaskRCNN_ResNet50_FPN_V2_Weights
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor


import sys
sys.path.append('./coco-text')
# import coco_text

In [21]:
# Set the seed for generating random numbers in PyTorch, NumPy, and Python's random module.
seed = 1234
device = get_torch_device()
dtype = torch.float32
device, dtype

NameError: name 'set_seed' is not defined

In [23]:
model = maskrcnn_resnet50_fpn_v2(weights=MaskRCNN_ResNet50_FPN_V2_Weights.DEFAULT)
model.eval()
summary(model, input_size=(3, 800, 800))

AttributeError: 'ImageList' object has no attribute 'size'

In [13]:
total_params = sum(p.numel() for p in model.parameters())
print(f'Total number of parameters: {total_params}')

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Number of trainable parameters: {trainable_params}')

Total number of parameters: 46359409
Number of trainable parameters: 46134065

In [6]:
# The name for the project
project_name = f"project-mask-rcnn-ocr"

# The path for the project folder
project_dir = Path(f"./{project_name}/")

# Create the project directory if it does not already exist
project_dir.mkdir(parents=True, exist_ok=True)

# Define path to store datasets
dataset_dir = Path("./Datasets/")
# Create the dataset directory if it does not exist
dataset_dir.mkdir(parents=True, exist_ok=True)

pd.Series({
    "Project Directory:": project_dir, 
    "Dataset Directory:": dataset_dir
}).to_frame().style.hide(axis='columns')

In [7]:
# Create the path to the directory where the dataset will be extracted
dataset_path = Path(f'{dataset_dir}/train2014')

# Get a list of image files in the dataset
img_file_paths = get_img_files(dataset_path)

json_file_path = f'./{dataset_dir}/cocotext.v2.json'

# Display the names of the folders using a Pandas DataFrame
pd.DataFrame({"Image File": [file.name for file in img_file_paths]}).head()
json_file_path

'./Datasets/cocotext.v2.json'

In [8]:
ct = coco_text.COCO_Text(json_file_path)

loading annotations into memory...
0:00:00.941641
creating index...
index created!

In [9]:
with open(json_file_path, 'r') as f:
    data = json.load(f)

In [10]:
for item in data['cats'].items():
    print(item)
    break

In [13]:
# # Load the data from the cocotext.v2.json file
# with open(f'{dataset_dir}/cocotext.v2.json', 'r') as f:
#     data = json.load(f)
# # ct = coco_text.COCO_Text(f'{dataset_dir}/cocotext.v2.json')
# Initialize an empty list to store the dictionaries
image_annotations = []
file_set = set(file.name for file in img_file_paths)

# Iterate over the annotations in the data
for img_id, annotation in ct.imgs.items():
    # Create a dictionary with the image file name and the annotation
    # Iterate over the annotations in img_file_paths
    if annotation['file_name'] in file_set:
        fn = annotation['file_name']

    image_annotation = {"file_name":fn,
                        "image_iD": img_id, "annotation": annotation}


    # Append the dictionary to the list
    image_annotations.append(image_annotation)


# Convert the list of dictionaries into a pandas DataFrame
annotation_df = pd.DataFrame(image_annotations)

# annotation_df['index'] = annotation_df.apply(lambda row: row['imagePath'].split('.')[0], axis=1)
# annotation_df = annotation_df.set_index('index')
# annotation_df['index'] = 
# Display the first few rows of the DataFrame
annotation_df.head()

,file_name,image_iD,annotation
0,COCO_train2014_000000540965.jpg,540965,"{'id': 540965, 'set': 'train', 'width': 640, 'file_name': 'COCO_train2014_000000540965.jpg', 'height': 360}"
1,COCO_train2014_000000229078.jpg,229078,"{'id': 229078, 'set': 'train', 'width': 640, 'file_name': 'COCO_train2014_000000229078.jpg', 'height': 480}"
2,COCO_train2014_000000260932.jpg,260932,"{'id': 260932, 'set': 'train', 'width': 640, 'file_name': 'COCO_train2014_000000260932.jpg', 'height': 512}"
3,COCO_train2014_000000103812.jpg,103812,"{'id': 103812, 'set': 'train', 'width': 640, 'file_name': 'COCO_train2014_000000103812.jpg', 'height': 427}"
4,COCO_train2014_000000304937.jpg,304937,"{'id': 304937, 'set': 'train', 'width': 640, 'file_name': 'COCO_train2014_000000304937.jpg', 'height': 640}"

In [ ]:
with open(json_file_path, 'r') as json_file:
    annotation_df = pd.read_json(json_file)

# Assign the image file name as the index for each row
# annotation_df['index'] = annotation_df.apply(lambda row: row['file_name'].split('.')[0], axis=1)
# annotation_df = annotation_df.set_index('index')

annotation_df.head()

,cats,anns,imgs,imgToAnns,info
45346,NaN,"{'mask': [468.9, 286.7, 468.9, 295.2, 493.0, 295.8, 493.0, 287.2], 'class': 'machine printed', 'bbox': [468.9, 286.7, 24.1, 9.1], 'image_id': 217925, 'id': 45346, 'language': 'english', 'area': 206.06, 'utf8_string': 'New', 'legibility': 'legible'}",NaN,NaN,NaN
153036,NaN,"{'mask': [344.5, 261.5, 348.1, 261.5, 348.2, 263.4, 344.5, 263.4], 'class': 'machine printed', 'bbox': [344.5, 261.5, 3.7, 1.9000000000000001], 'image_id': 483569, 'id': 153036, 'language': 'english', 'area': 6.93, 'utf8_string': '', 'legibility': 'illegible'}",NaN,NaN,NaN
125303,NaN,"{'mask': [362.4, 280.9, 359.2, 286.3, 367.1, 291.0, 369.9, 285.0], 'class': 'machine printed', 'bbox': [359.2, 280.9, 10.7, 10.1], 'image_id': 417153, 'id': 125303, 'language': 'english', 'area': 57.09, 'utf8_string': '', 'legibility': 'illegible'}",NaN,NaN,NaN
21639,NaN,"{'mask': [570.9, 9.6, 570.9, 14.3, 557.1, 14.3, 556.8, 9.4], 'class': 'machine printed', 'bbox': [556.8, 9.4, 14.1, 4.9], 'image_id': 15451, 'id': 21639, 'language': 'english', 'area': 66.94, 'utf8_string': '', 'legibility': 'illegible'}",NaN,NaN,NaN
112792,NaN,"{'mask': [489.4, 131.8, 502.7, 135.6, 502.7, 156.4, 493.1, 155.3], 'class': 'machine printed', 'bbox': [489.4, 131.8, 13.3, 24.6], 'image_id': 379024, 'id': 112792, 'language': 'english', 'area': 249.08, 'utf8_string': 'W', 'legibility': 'legible'}",NaN,NaN,NaN

In [ ]:
ct.anns

{45346: {'mask': [468.9, 286.7, 468.9, 295.2, 493.0, 295.8, 493.0, 287.2],
  'class': 'machine printed',
  'bbox': [468.9, 286.7, 24.1, 9.1],
  'image_id': 217925,
  'id': 45346,
  'language': 'english',
  'area': 206.06,
  'utf8_string': 'New',
  'legibility': 'legible'},
 153036: {'mask': [344.5, 261.5, 348.1, 261.5, 348.2, 263.4, 344.5, 263.4],
  'class': 'machine printed',
  'bbox': [344.5, 261.5, 3.7, 1.9],
  'image_id': 483569,
  'id': 153036,
  'language': 'english',
  'area': 6.93,
  'utf8_string': '',
  'legibility': 'illegible'},
 125303: {'mask': [362.4, 280.9, 359.2, 286.3, 367.1, 291.0, 369.9, 285.0],
  'class': 'machine printed',
  'bbox': [359.2, 280.9, 10.7, 10.1],
  'image_id': 417153,
  'id': 125303,
  'language': 'english',
  'area': 57.09,
  'utf8_string': '',
  'legibility': 'illegible'},
 21639: {'mask': [570.9, 9.6, 570.9, 14.3, 557.1, 14.3, 556.8, 9.4],
  'class': 'machine printed',
  'bbox': [556.8, 9.4, 14.1, 4.9],
  'image_id': 15451,
  'id': 21639,
  'language': 'english',
  'area': 66.94,
  'utf8_string': '',
  'legibility': 'illegible'},
 112792: {'mask': [489.4, 131.8, 502.7, 135.6, 502.7, 156.4, 493.1, 155.3],
  'class': 'machine printed',
  'bbox': [489.4, 131.8, 13.3, 24.6],
  'image_id': 379024,
  'id': 112792,
  'language': 'english',
  'area': 249.08,
  'utf8_string': 'W',
  'legibility': 'legible'},
 63773: {'mask': [105.3, 98.6, 105.3, 104.0, 111.0, 102.5, 111.3, 98.3],
  'class': 'machine printed',
  'bbox': [105.3, 98.3, 6.0, 5.7],
  'image_id': 260285,
  'id': 63773,
  'language': 'english',
  'area': 27.95,
  'utf8_string': '',
  'legibility': 'illegible'},
 8231: {'mask': [577.8, 148.3, 601.7, 149.1, 611.0, 196.2, 575.7, 193.9],
  'class': 'machine printed',
  'bbox': [575.7, 148.3, 35.3, 47.9],
  'image_id': 122908,
  'id': 8231,
  'language': 'english',
  'area': 1366.38,
  'utf8_string': 'NAVY',
  'legibility': 'legible'},
 20812: {'mask': [143.1, 265.4, 163.0, 265.1, 163.0, 268.7, 144.0, 269.3],
  'class': 'machine printed',
  'bbox': [143.1, 265.1, 19.9, 4.2],
  'image_id': 1526,
  'id': 20812,
  'language': 'english',
  'area': 73.14,
  'utf8_string': '',
  'legibility': 'illegible'},
 62004: {'mask': [381.6, 228.8, 380.9, 233.0, 397.7, 234.2, 398.9, 229.7],
  'class': 'machine printed',
  'bbox': [380.9, 228.8, 18.0, 5.4],
  'image_id': 257013,
  'id': 62004,
  'language': 'english',
  'area': 75.16,
  'utf8_string': '',
  'legibility': 'illegible'},
 74301: {'mask': [535.5,
   393.8,
   533.1,
   421.0,
   548.3,
   417.8,
   552.3,
   409.0,
   569.1,
   409.8,
   585.9,
   413.0,
   589.9,
   419.4,
   597.9,
   417.8,
   602.7,
   409.8,
   607.5,
   409.8,
   607.5,
   419.4,
   620.3,
   419.4,
   626.7,
   393.8],
  'class': 'machine printed',
  'bbox': [533.1, 393.8, 93.6, 27.2],
  'image_id': 285194,
  'id': 74301,
  'language': 'english',
  'area': 1863.04,
  'utf8_string': ' ',
  'legibility': 'illegible'},
 168131: {'mask': [153.5, 204.6, 153.2, 210.1, 161.2, 212.9, 161.5, 208.6],
  'class': 'machine printed',
  'bbox': [153.2, 204.6, 8.3, 8.3],
  'image_id': 52484,
  'id': 168131,
  'language': 'english',
  'area': 40.22,
  'utf8_string': '',
  'legibility': 'illegible'},
 186796: {'mask': [180.2, 306.1, 183.7, 309.2, 205.9, 298.6, 205.4, 294.1],
  'class': 'machine printed',
  'bbox': [180.2, 294.1, 25.7, 15.1],
  'image_id': 574025,
  'id': 186796,
  'language': 'english',
  'area': 112.66,
  'utf8_string': '',
  'legibility': 'illegible'},
 18187: {'mask': [-1.6, 141.5, -1.9, 158.8, 28.4, 158.5, 28.1, 140.6],
  'class': 'machine printed',
  'bbox': [-1.9, 140.6, 30.3, 18.2],
  'image_id': 145757,
  'id': 18187,
  'language': 'english',
  'area': 528.0,
  'utf8_string': '',
  'legibility': 'illegible'},
 175298: {'mask': [398.7, 16.5, 385.0, 18.2, 387.1, 48.7, 401.7, 45.3],
  'class': 'machine printed',
  'bbox': [385.0, 16.5, 16.7, 32.2],
  'image_id': 544815,
  'id': 175298,
  'language': 'english',
  'area': 426.05,
  'utf8_string': '6',
  'legibility': 'legible'},
 45309: {'mask': [43.7, 246.9, 43.4, 253.3, 88.1, 253.6, 88.1, 246.9],
  'class': 'machine printed',
  'bbox': [43.4, 246.9, 44.7, 6.7],
  'image_id': 217925,
  'id': 45309,
  'language': 'english',
  'area': 291.82,
  'utf8_string': '',
  'legibility': 'illegible'},
 125471: {'mask': [385.2,
   53.8,
   383.9,
   66.2,
   393.8,
   67.1,
   393.8,
   61.2,
   400.6,
   62.5,
   401.8,
   56.0],
  'class': 'machine printed',
  'bbox': [383.9, 53.8, 17.9, 13.3],
  'image_id': 417556,
  'id': 125471,
  'language': 'english',
  'area': 162.18,
  'utf8_string': '$189',
  'legibility': 'legible'},
 151985: {'mask': [52.3, 177.1, 66.1, 175.6, 65.4, 182.3, 52.3, 183.5],
  'class': 'machine printed',
  'bbox': [52.3, 175.6, 13.8, 7.9],
  'image_id': 481462,
  'id': 151985,
  'language': 'english',
  'area': 87.63,
  'utf8_string': '',
  'legibility': 'illegible'},
 866: {'mask': [80.0, 114.1, 83.1, 124.5, 113.8, 117.7, 110.9, 107.3],
  'class': 'machine printed',
  'bbox': [80.0, 107.3, 33.8, 17.2],
  'image_id': 102288,
  'id': 866,
  'language': 'english',
  'area': 340.72,
  'utf8_string': 'KCAL',
  'legibility': 'legible'},
 3071: {'mask': [126.3, 180.9, 123.6, 193.3, 91.2, 197.5, 89.2, 186.0],
  'class': 'machine printed',
  'bbox': [89.2, 180.9, 37.1, 16.6],
  'image_id': 107975,
  'id': 3071,
  'language': 'english',
  'area': 413.63,
  'utf8_string': '',
  'legibility': 'illegible'},
 129892: {'mask': [17.9, 318.5, 16.4, 328.4, 29.5, 328.6, 28.6, 319.8],
  'class': 'machine printed',
  'bbox': [16.4, 318.5, 13.1, 10.1],
  'image_id': 427150,
  'id': 129892,
  'language': 'english',
  'area': 111.49,
  'utf8_string': '',
  'legibility': 'illegible'},
 176775: {'mask': [560.9,
   123.5,
   559.3,
   135.9,
   571.7,
   131.6,
   580.0,
   133.4,
   588.7,
   135.0,
   598.5,
   140.2,
   601.6,
   145.4,
   604.7,
   136.2,
   598.2,
   130.3,
   590.2,
   126.9,
   577.9,
   123.2],
  'class': 'machine printed',
  'bbox': [559.3, 123.2, 45.4, 22.2],
  'image_id': 549017,
  'id': 176775,
  'language': 'english',
  'area': 415.92,
  'utf8_string': '',
  'legibility': 'illegible'},
 100365: {'mask': [357.5, 318.8, 352.2, 318.6, 352.0, 324.8, 357.5, 325.2],
  'class': 'machine printed',
  'bbox': [352.0, 318.6, 5.5, 6.6],
  'image_id': 3483,
  'id': 100365,
  'language': 'english',
  'area': 34.05,
  'utf8_string': 'O',
  'legibility': 'legible'},
 149280: {'mask': [330.6, 95.4, 330.6, 100.3, 366.2, 99.9, 365.8, 95.6],
  'class': 'machine printed',
  'bbox': [330.6, 95.4, 35.6, 4.9],
  'image_id': 475485,
  'id': 149280,
  'language': 'english',
  'area': 162.86,
  'utf8_string': 'INCREMENTE',
  'legibility': 'legible'},
 179243: {'mask': [177.0, 176.2, 185.3, 181.5, 203.2, 174.4, 196.4, 167.3],
  'class': 'machine printed',
  'bbox': [177.0, 167.3, 26.2, 14.2],
  'image_id': 554729,
  'id': 179243,
  'language': 'english',
  'area': 176.03,
  'utf8_string': '',
  'legibility': 'illegible'},
 74405: {'mask': [413.2, 90.5, 385.8, 106.4, 375.4, 102.4, 405.1, 89.8],
  'class': 'machine printed',
  'bbox': [375.4, 89.8, 37.8, 16.6],
  'image_id': 285477,
  'id': 74405,
  'language': 'english',
  'area': 198.91,
  'utf8_string': '',
  'legibility': 'illegible'},
 175241: {'mask': [228.8, 267.0, 235.4, 266.9, 235.1, 269.3, 228.4, 269.3],
  'class': 'machine printed',
  'bbox': [228.4, 266.9, 7.0, 2.4],
  'image_id': 544732,
  'id': 175241,
  'language': 'english',
  'area': 15.61,
  'utf8_string': '',
  'legibility': 'illegible'},
 36019: {'mask': [388.3, 196.1, 389.2, 203.2, 413.2, 203.2, 414.1, 196.1],
  'class': 'machine printed',
  'bbox': [388.3, 196.1, 25.8, 7.1],
  'image_id': 193479,
  'id': 36019,
  'language': 'english',
  'area': 176.79,
  'utf8_string': 'LONDON',
  'legibility': 'legible'},
 86668: {'mask': [518.4, 99.9, 520.0, 111.5, 540.7, 107.6, 539.2, 96.1],
  'class': 'machine printed',
  'bbox': [518.4, 96.1, 22.3, 15.4],
  'image_id': 314398,
  'id': 86668,
  'language': 'english',
  'area': 245.63,
  'utf8_string': '97',
  'legibility': 'legible'},
 161883: {'mask': [418.2, 404.6, 418.2, 414.3, 462.1, 418.0, 462.1, 411.6],
  'class': 'machine printed',
  'bbox': [418.2, 404.6, 43.9, 13.4],
  'image_id': 509700,
  'id': 161883,
  'language': 'english',
  'area': 353.39,
  'utf8_string': '',
  'legibility': 'illegible'},
 174648: {'mask': [505.3,
   6.5,
   505.3,
   6.5,
   531.9,
   6.5,
   532.2,
   10.9,
   525.2,
   18.7,
   504.9,
   17.9],
  'class': 'machine printed',
  'bbox': [504.9, 6.5, 27.3, 12.2],
  'image_id': 54304,
  'id': 174648,
  'language': 'english',
  'area': 294.7,
  'utf8_string': 'RVP',
  'legibility': 'legible'},
 192046: {'mask': [1.7, 201.3, 1.7, 213.6, 10.3, 213.0, 10.3, 201.6],
  'class': 'machine printed',
  'bbox': [1.7, 201.3, 8.6, 12.3],
  'image_id': 63820,
  'id': 192046,
  'language': 'english',
  'area': 101.91,
  'utf8_string': '',
  'legibility': 'illegible'},
 91961: {'mask': [152.0, 215.6, 150.1, 220.3, 180.1, 217.5, 180.7, 214.4],
  'class': 'machine printed',
  'bbox': [150.1, 214.4, 30.6, 5.9],
  'image_id': 327576,
  'id': 91961,
  'language': 'english',
  'area': 111.97,
  'utf8_string': '',
  'legibility': 'illegible'},
 12881: {'mask': [3.3,
   404.3,
   12.2,
   415.5,
   35.8,
   396.2,
   41.5,
   402.8,
   53.5,
   393.2,
   47.3,
   363.8],
  'class': 'machine printed',
  'bbox': [3.3, 363.8, 50.2, 51.7],
  'image_id': 133509,
  'id': 12881,
  'language': 'english',
  'area': 1034.42,
  'utf8_string': '',
  'legibility': 'illegible'},
 72786: {'mask': [154.7, 197.9, 147.9, 201.5, 147.0, 219.1, 153.0, 216.0],
  'class': 'machine printed',
  'bbox': [147.0, 197.9, 7.7, 21.2],
  'image_id': 281774,
  'id': 72786,
  'language': 'english',
  'area': 109.88,
  'utf8_string': 'The',
  'legibility': 'legible'},
 52722: {'mask': [450.4,
   237.1,
   483.9,
   228.6,
   493.4,
   241.6,
   488.4,
   240.6,
   465.4,
   248.6],
  'class': 'machine printed',
  'bbox': [450.4, 228.6, 43.0, 20.0],
  'image_id': 235043,
  'id': 52722,
  'language': 'english',
  'area': 440.12,
  'utf8_string': 'Vegan',
  'legibility': 'legible'},
 184641: {'mask': [532.2, 282.9, 532.2, 289.3, 553.8, 288.4, 552.9, 283.5],
  'class': 'machine printed',
  'bbox': [532.2, 282.9, 21.6, 6.4],
  'image_id': 568311,
  'id': 184641,
  'language': 'english',
  'area': 119.56,
  'utf8_string': '',
  'legibility': 'illegible'},
 76322: {'mask': [121.1, 296.8, 119.2, 302.4, 136.6, 308.6, 138.5, 304.3],
  'class': 'machine printed',
  'bbox': [119.2, 296.8, 19.3, 11.8],
  'image_id': 290246,
  'id': 76322,
  'language': 'english',
  'area': 99.14,
  'utf8_string': '',
  'legibility': 'illegible'},
 528: {'mask': [94.0, 554.3, 93.7, 560.2, 98.3, 560.2, 98.3, 554.0],
  'class': 'machine printed',
  'bbox': [93.7, 554.0, 4.6, 6.2],
  'image_id': 10136,
  'id': 528,
  'language': 'english',
  'area': 26.9,
  'utf8_string': '',
  'legibility': 'illegible'},
 29873: {'mask': [109.7,
   289.8,
   107.8,
   295.3,
   121.2,
   300.0,
   146.2,
   297.7,
   145.8,
   295.3,
   140.7,
   293.0,
   127.3,
   293.0],
  'class': 'machine printed',
  'bbox': [107.8, 289.8, 38.4, 10.2],
  'image_id': 176767,
  'id': 29873,
  'language': 'english',
  'area': 230.31,
  'utf8_string': ' ',
  'legibility': 'illegible'},
 192497: {'mask': [61.6,
   461.6,
   62.5,
   472.5,
   76.4,
   474.3,
   86.6,
   476.4,
   95.4,
   480.0,
   109.2,
   486.6,
   116.2,
   493.6,
   116.5,
   476.7,
   102.0,
   465.8,
   83.6,
   460.4,
   65.8,
   458.0],
  'class': 'machine printed',
  'bbox': [61.6, 458.0, 54.9, 35.6],
  'image_id': 64730,
  'id': 192497,
  'language': 'english',
  'area': 844.04,
  'utf8_string': 'PRETZELS',
  'legibility': 'legible'},
 184210: {'mask': [176.4, 521.1, 176.8, 528.3, 208.0, 527.7, 208.5, 523.1],
  'class': 'machine printed',
  'bbox': [176.4, 521.1, 32.1, 7.2],
  'image_id': 567240,
  'id': 184210,
  'language': 'english',
  'area': 186.77,
  'utf8_string': '',
  'legibility': 'illegible'},
 167312: {'mask': [216.3, 36.7, 216.5, 42.7, 226.1, 42.5, 225.5, 36.7],
  'class': 'machine printed',
  'bbox': [216.3, 36.7, 9.8, 6.0],
  'image_id': 522579,
  'id': 167312,
  'language': 'english',
  'area': 55.5,
  'utf8_string': 'the',
  'legibility': 'legible'},
 113470: {'mask': [463.2,
   229.5,
   467.0,
   221.9,
   469.0,
   211.6,
   469.4,
   205.8,
   459.8,
   198.2,
   459.6,
   212.5,
   456.5,
   225.9],
  'class': 'machine printed',
  'bbox': [456.5, 198.2, 12.9, 31.3],
  'image_id': 380524,
  'id': 113470,
  'language': 'english',
  'area': 240.44,
  'utf8_string': '',
  'legibility': 'illegible'},
 73459: {'mask': [524.9, 250.5, 523.6, 256.5, 536.9, 256.7, 537.3, 251.4],
  'class': 'machine printed',
  'bbox': [523.6, 250.5, 13.7, 6.2],
  'image_id': 283122,
  'id': 73459,
  'language': 'english',
  'area': 73.07,
  'utf8_string': '',
  'legibility': 'illegible'},
 14933: {'mask': [-0.7, 194.5, 4.9, 193.7, 6.0, 211.9, -0.7, 211.9],
  'class': 'machine printed',
  'bbox': [-0.7, 193.7, 6.7, 18.2],
  'image_id': 138579,
  'id': 14933,
  'language': 'english',
  'area': 109.69,
  'utf8_string': 'S',
  'legibility': 'legible'},
 14462: {'mask': [311.8, 383.9, 320.9, 383.1, 321.5, 386.6, 312.6, 387.4],
  'class': 'machine printed',
  'bbox': [311.8, 383.1, 9.7, 4.3],
  'image_id': 137382,
  'id': 14462,
  'language': 'english',
  'area': 32.06,
  'utf8_string': '',
  'legibility': 'illegible'},
 9964: {'mask': [328.6, 195.9, 329.0, 205.7, 369.1, 206.6, 369.1, 196.7],
  'class': 'machine printed',
  'bbox': [328.6, 195.9, 40.5, 10.7],
  'image_id': 126647,
  'id': 9964,
  'language': 'english',
  'area': 396.78,
  'utf8_string': 'Compose',
  'legibility': 'legible'},
 54512: {'mask': [157.5, 292.1, 157.3, 303.9, 202.6, 303.6, 202.0, 294.1],
  'class': 'machine printed',
  'bbox': [157.3, 292.1, 45.3, 11.8],
  'image_id': 238757,
  'id': 54512,
  'language': 'english',
  'area': 478.01,
  'utf8_string': 'ATHLETE',
  'legibility': 'legible'},
 86492: {'mask': [552.5, 268.2, 575.7, 281.8, 598.9, 222.6, 588.5, 218.6],
  'class': 'machine printed',
  'bbox': [552.5, 218.6, 46.4, 63.2],
  'image_id': 313956,
  'id': 86492,
  'language': 'english',
  'area': 1174.4,
  'utf8_string': '',
  'legibility': 'illegible'},
 198534: {'mask': [392.5,
   322.5,
   391.6,
   326.3,
   418.1,
   325.9,
   419.4,
   322.5,
   392.1,
   322.0],
  'class': 'machine printed',
  'bbox': [391.6, 322.0, 27.8, 4.3],
  'image_id': 82513,
  'id': 198534,
  'language': 'english',
  'area': 102.62,
  'utf8_string': '',
  'legibility': 'illegible'},
 50829: {'mask': [114.8, 239.1, 115.2, 243.6, 135.8, 244.7, 135.8, 241.4],
  'class': 'machine printed',
  'bbox': [114.8, 239.1, 21.0, 5.6],
  'image_id': 230209,
  'id': 50829,
  'language': 'english',
  'area': 80.78,
  'utf8_string': '',
  'legibility': 'illegible'},
 28670: {'mask': [10.8, 109.3, 10.8, 113.6, 30.6, 116.0, 31.5, 110.8],
  'class': 'machine printed',
  'bbox': [10.8, 109.3, 20.7, 6.7],
  'image_id': 173759,
  'id': 28670,
  'language': 'english',
  'area': 97.06,
  'utf8_string': '',
  'legibility': 'illegible'},
 88355: {'mask': [382.9, 171.6, 380.2, 181.7, 372.5, 180.5, 374.1, 170.9],
  'class': 'machine printed',
  'bbox': [372.5, 170.9, 10.4, 10.8],
  'image_id': 318279,
  'id': 88355,
  'language': 'english',
  'area': 83.3,
  'utf8_string': 'S',
  'legibility': 'legible'},
 20065: {'mask': [319.3, 106.3, 361.3, 97.7, 374.7, 370.3, 325.3, 379],
  'class': 'machine printed',
  'bbox': [319.3, 97.7, 55.4, 281.3],
  'image_id': 151115,
  'id': 20065,
  'language': 'english',
  'area': 12544.01,
  'utf8_string': 'HOTEL',
  'legibility': 'legible'},
 48997: {'mask': [386.7, 381.7, 385.6, 398.4, 422.2, 398.7, 426.3, 385.4],
  'class': 'machine printed',
  'bbox': [385.6, 381.7, 40.7, 17.0],
  'image_id': 225584,
  'id': 48997,
  'language': 'english',
  'area': 576.7,
  'utf8_string': 'Herald',
  'legibility': 'legible'},
 76668: {'mask': [203.2,
   264.0,
   203.2,
   264.0,
   211.5,
   274.6,
   226.5,
   259.6,
   219.9,
   252.3,
   217.1,
   250.7],
  'class': 'machine printed',
  'bbox': [203.2, 250.7, 23.3, 23.9],
  'image_id': 291056,
  'id': 76668,
  'language': 'english',
  'area': 271.06,
  'utf8_string': 'CO',
  'legibility': 'legible'},
 97125: {'mask': [392.1, 59.1, 392.1, 75.8, 418.0, 79.9, 417.6, 62.8],
  'class': 'machine printed',
  'bbox': [392.1, 59.1, 25.9, 20.8],
  'image_id': 33891,
  'id': 97125,
  'language': 'english',
  'area': 433.55,
  'utf8_string': '10',
  'legibility': 'legible'},
 191176: {'mask': [294.3, 150.0, 292.1, 156.3, 300.7, 159.5, 303.6, 152.9],
  'class': 'machine printed',
  'bbox': [292.1, 150.0, 11.5, 9.5],
  'image_id': 61560,
  'id': 191176,
  'language': 'english',
  'area': 65.5,
  'utf8_string': '',
  'legibility': 'illegible'},
 57432: {'mask': [170.3, 540.9, 184.6, 540.0, 184.6, 547.6, 170.8, 547.6],
  'class': 'machine printed',
  'bbox': [170.3, 540.0, 14.3, 7.6],
  'image_id': 246573,
  'id': 57432,
  'language': 'english',
  'area': 100.57,
  'utf8_string': '',
  'legibility': 'illegible'},
 7235: {'mask': [243.4,
   202.6,
   243.4,
   202.6,
   243.5,
   207.9,
   258.4,
   208.2,
   258.4,
   202.6],
  'class': 'machine printed',
  'bbox': [243.4, 202.6, 15.0, 5.6],
  'image_id': 119808,
  'id': 7235,
  'language': 'english',
  'area': 81.47,
  'utf8_string': '',
  'legibility': 'illegible'},
 73258: {'mask': [196.9, 152.1, 194.8, 156.2, 210.4, 157.4, 210.4, 151.9],
  'class': 'machine printed',
  'bbox': [194.8, 151.9, 15.6, 5.5],
  'image_id': 282670,
  'id': 73258,
  'language': 'english',
  'area': 70.36,
  'utf8_string': '',
  'legibility': 'illegible'},
 13423: {'mask': [436.3, 606.7, 346.3, 606.7, 347.3, 624.7, 437.9, 623.2],
  'class': 'machine printed',
  'bbox': [346.3, 606.7, 91.6, 18.0],
  'image_id': 135229,
  'id': 13423,
  'language': 'english',
  'area': 1558.65,
  'utf8_string': 'snowbird',
  'legibility': 'legible'},
 72971: {'mask': [192.1,
   362.0,
   198.3,
   379.7,
   207.1,
   378.9,
   201.3,
   362.0,
   194.0,
   362.0],
  'class': 'machine printed',
  'bbox': [192.1, 362.0, 15.0, 17.7],
  'image_id': 282208,
  'id': 72971,
  'language': 'english',
  'area': 158.1,
  'utf8_string': '',
  'legibility': 'illegible'},
 34434: {'mask': [105.6, 395.5, 95.4, 411.4, 149.4, 422.5, 153.2, 399.4],
  'class': 'machine printed',
  'bbox': [95.4, 395.5, 57.8, 27.0],
  'image_id': 189094,
  'id': 34434,
  'language': 'english',
  'area': 1043.1,
  'utf8_string': 'Charging',
  'legibility': 'legible'},
 58897: {'mask': [37.4, 161.9, 37.4, 166.1, 53.9, 167.5, 54.2, 162.8],
  'class': 'machine printed',
  'bbox': [37.4, 161.9, 16.8, 5.6],
  'image_id': 24980,
  'id': 58897,
  'language': 'english',
  'area': 74.26,
  'utf8_string': '',
  'legibility': 'illegible'},
 116110: {'mask': [5.7, 397.4, 5.7, 401.4, 20.0, 399.8, 20.0, 396.5],
  'class': 'machine printed',
  'bbox': [5.7, 396.5, 14.3, 4.9],
  'image_id': 3877,
  'id': 116110,
  'language': 'english',
  'area': 52.2,
  'utf8_string': '',
  'legibility': 'illegible'},
 6664: {'mask': [476.6, 219.6, 481.8, 248.1, 485.1, 248.1, 481.8, 217.7],
  'class': 'machine printed',
  'bbox': [476.6, 217.7, 8.5, 30.4],
  'image_id': 11826,
  'id': 6664,
  'language': 'english',
  'area': 129.2,
  'utf8_string': '',
  'legibility': 'illegible'},
 6494: {'mask': [346.5, 172.1, 346.9, 178.6, 363.8, 178.6, 362.3, 171.8],
  'class': 'machine printed',
  'bbox': [346.5, 171.8, 17.3, 6.8],
  'image_id': 117781,
  'id': 6494,
  'language': 'english',
  'area': 108.87,
  'utf8_string': '',
  'legibility': 'illegible'},
 190256: {'mask': [368.0, 453.2, 369.6, 456.7, 395.3, 444.2, 393.1, 440.0],
  'class': 'machine printed',
  'bbox': [368.0, 440.0, 27.3, 16.7],
  'image_id': 5883,
  'id': 190256,
  'language': 'english',
  'area': 122.2,
  'utf8_string': '',
  'legibility': 'illegible'},
 22049: {'mask': [101.7,
   283.4,
   101.7,
   283.4,
   101.7,
   287.1,
   101.7,
   287.1,
   120.6,
   283.0,
   120.6,
   283.0,